In [13]:
import numpy as np

In [88]:
import cv2
image= cv2.imread(r'C:\Users\AMZ PC\OneDrive\Desktop\CV\istockphoto-1443562748-612x612.jpg')

# Display the image in a window
cv2.imshow("Image", image)

# Wait for a key press indefinitely or for a specific amount of time
cv2.waitKey(0)  # 0 means wait indefinitely

# Close the image window
cv2.destroyAllWindows()

In [65]:
image.shape

(531, 612, 3)

In [70]:
bg_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)


In [71]:
img = cv2.resize(bg_img, (64, 128))
cv2.imshow("Image", image)

# Wait for a key press indefinitely or for a specific amount of time
cv2.waitKey(0)  # 0 means wait indefinitely

# Close the image window
cv2.destroyAllWindows()

In [76]:
# def get_patches(image, patch_size=(3, 3)):
    
#     patches = []
#     patch_height, patch_width = patch_size
#     for i in range(0, image.shape[0] - patch_height + 1, patch_height):
#         for j in range(0, image.shape[1] - patch_width + 1, patch_width):
#             patch = image[i:i + patch_height, j:j + patch_width]
#             patches.append(patch)
#     return patches
# get_patches(img)
print(img)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [90]:
# Gx=None
# Gy=None
def calc_pixel_gradients(img):
    # global Gx, Gy
    
    Gx = np.zeros_like(img)
    Gy = np.zeros_like(img)
    
    for i in range(1, img.shape[0] - 1):
        for j in range(1, img.shape[1] - 1):
            Gx[i, j] = img[i, j + 1] - img[i, j - 1]
            Gy[i, j] = img[i + 1, j] - img[i - 1, j]
    
    return Gx, Gy


In [96]:
grad_x,grad_y=calc_pixel_gradients(img)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


C:\Users\AMZ PC\AppData\Local\Temp\ipykernel_9392\299825726.py:12: RuntimeWarning: overflow encountered in scalar subtract
  Gy[i, j] = img[i + 1, j] - img[i - 1, j]
C:\Users\AMZ PC\AppData\Local\Temp\ipykernel_9392\299825726.py:11: RuntimeWarning: overflow encountered in scalar subtract
  Gx[i, j] = img[i, j + 1] - img[i, j - 1]


In [98]:
def magnitude(image, grad_x, grad_y):
    global magnitude
    magnitude = np.sqrt(grad_x**2 + grad_y**2) #using pythagoras
    return magnitude
def direction(image, grad_x, grad_y):
    global orientation
    orientation = np.arctan2(grad_y, grad_x) * (180 / np.pi)  # Convert to degrees
    return direction


In [99]:
mag=magnitude(img, grad_x, grad_y)
dir=direction(img, grad_x, grad_y)

In [100]:
magnitude(image,grad_x, grad_y)
direction(image,grad_x, grad_y)
# Define parameters for HOG
cell_size = 8  # 8x8 pixels per cell
bin_size = 20  # 20-degree bins
num_bins = 9   # 9 bins (0-20, 20-40, ..., 160-180)

# Calculate HOG for each cell
hog_features = []
for i in range(0, image.shape[0], cell_size):
    for j in range(0, image.shape[1], cell_size):
        cell_magnitude = magnitude[i:i+cell_size, j:j+cell_size]
        cell_orientation = orientation[i:i+cell_size, j:j+cell_size]
        
        # Create histogram for the current cell
        hist = np.zeros(num_bins)
        for x in range(cell_size):
            for y in range(cell_size):
                # Determine the bin for each pixel's orientation
                bin_index = int(cell_orientation[x, y] // bin_size)
                hist[bin_index] += cell_magnitude[x, y]
        
        # Append the histogram to the HOG features
        hog_features.append(hist)

# Convert the list of histograms to a single feature vector
hog_features = np.concatenate(hog_features)

# Print the HOG feature vector
print("HOG feature vector:", hog_features)

# Plotting the histogram for one cell
import matplotlib.pyplot as plt

# Select the histogram of the first cell for demonstration
plt.bar(range(num_bins), hog_features[:num_bins])
plt.xlabel("Orientation Bins")
plt.ylabel("Magnitude Sum")
plt.title("Histogram of Oriented Gradients for the First Cell")
plt.show()

TypeError: 'numpy.ndarray' object is not callable